## Tasca 4: Pràctica amb programació numèrica - Eduardo Baffi

#### Nivell 1

In [58]:
# - Exercici 1
# Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. 
# Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

import numpy as np
import scipy.stats

def basic_statistics(array):
    if array.ndim > 1:
        print("Error! Array tiene más de una dimensió. Comproba tus datos y intenta de nuevo.")
    else:
        print(scipy.stats.describe(array))
    
yourarray = np.random.rand(10)*10
print("Ejemplo de array de una dimensión:")
print(yourarray)
print()
print("Resumen estadístico básico de los datos:")
basic_statistics(yourarray)
print()

yourarray2 = np.random.rand(2,2)*10
print("Ejemplo de array de más de una dimensión:")
print(yourarray2)

basic_statistics(yourarray2)



############
# Exercici 1 - Solución alternativa solamente con numpy
import statistics 

def basic_statistics_2(array):
    if array.ndim > 1:
        print("Error! Array tiene más de una dimensió. Comproba tus datos y intenta de nuevo.")
    else:
        print("Mean: " + str(np.mean(array)))               #Datos estadísticos
        print("Average: " + str(np.average(array)))
        print("Median: " + str(np.median(array)))
        print("Mode: " + str(statistics.mode(array)))
        print("Standard Deviation: " + str(np.std(array)))
        print("Variance: " + str(np.var(array)))
        print("Covariance: " + str(np.cov(array)))
        print("Minimum: " + str(np.amin(array)))
        print("Maximum: " + str(np.amax(array)))
        print("Range of values: " + str(np.ptp(array)))

print()
print("SOLUCIÓN ALTERNATIVA DEL EJERCICIO 1")    
yourarray = np.random.rand(10)*10
print("Ejemplo de array de una dimensión:")
print(yourarray)
print()
print("Resumen estadístico básico de los datos:")
basic_statistics_2(yourarray)
print()

yourarray2 = np.random.rand(2,2)*10
print("Ejemplo de array de más de una dimensión:")
print(yourarray2)

basic_statistics_2(yourarray2)


Ejemplo de array de una dimensión:
[3.02405277 8.11187553 0.43610907 8.32051689 1.09376817 5.61418702
 8.5508335  7.81572098 8.74889687 8.7588873 ]

Resumen estadístico básico de los datos:
DescribeResult(nobs=10, minmax=(0.43610907367890306, 8.758887304585745), mean=6.047484809426235, variance=10.980762534966367, skewness=-0.7871857774707207, kurtosis=-1.0766924063296621)

Ejemplo de array de más de una dimensión:
[[4.5602249  7.00545385]
 [8.14811287 1.10105792]]
Error! Array tiene más de una dimensió. Comproba tus datos y intenta de nuevo.

SOLUCIÓN ALTERNATIVA DEL EJERCICIO 1
Ejemplo de array de una dimensión:
[3.924317   6.68538208 5.30882198 3.38052113 1.97103584 3.21067726
 0.81261051 5.71272102 7.22178585 7.89796908]

Resumen estadístico básico de los datos:
Mean: 4.612584175813752
Average: 4.612584175813752
Median: 4.616569492167926
Mode: 3.924317003865032
Standard Deviation: 2.212867781287788
Variance: 4.896783817461538
Covariance: 5.440870908290597
Minimum: 0.812610507477861

In [66]:
# - Exercici 2
# Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

import numpy as np


print("Cuadrado de números enteros aleatórios entre 0 y 100")
def square():
    N = int(input("Introduzca el número de elementos del cuadrado (N de una matriz NxN): "))
    randomArray = np.random.randint(0, 100, size=(N,N))
    print(np.around(randomArray,2))

square()

#####
# Solución para números float aleatórios entre 0 y 10

print()
print("Cuadrado de números float aleatórios entre 0 y 10")
def square_aleatory():
    num = int(input("Introduzca el número de elementos del cuadrado (N de una matriz NxN): "))
    randomArray = np.random.rand(num,num)*10
    print(np.around(randomArray,2))

square_aleatory()




Cuadrado de números enteros aleatórios entre 0 y 100
Introduzca el número de elementos del cuadrado (N de una matriz NxN): 6
[[32 10 24 94  5 11]
 [99 65 50 99 75 35]
 [89 50 87 31 19 81]
 [41 84 31 16 72 63]
 [13 72 80 54 88 59]
 [82 66 76 93 69 95]]

Cuadrado de números float aleatórios entre 0 y 10
Introduzca el número de elementos del cuadrado (N de una matriz NxN): 4
[[3.88 2.86 8.23 6.05]
 [8.74 2.53 8.63 9.82]
 [3.31 5.19 0.39 2.01]
 [3.16 3.53 5.64 1.64]]


In [71]:
# - Exercici 3
# Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

import numpy as np

print("Tabla 2-D")

def table_2D(array):
    print("Total por fila:")
    print(array.sum(axis=1))
    print()
    print("Total por columna: ")
    print(array.sum(axis=0))

#testArray = np.array([[1, 2, 3], [4, 5, 6]])     # Tabla fija para testear el programa

testArray = np.random.randint(100, size=(6,7))
print(testArray)
print()
table_2D(testArray)

Tabla 2-D
[[ 4 72 32  9 92 48 61]
 [ 9 52 28 50 68 43 78]
 [81 51 71 35 79 59 86]
 [63 49 64 15 17 61 34]
 [71 74 97 22 35 82 78]
 [15 18 19 94 15 63  3]]

Total por fila:
[318 328 462 303 459 227]

Total por columna: 
[243 316 311 225 306 356 340]


In [114]:
# - Exercici 4
# Implementa manualment una funció que calculi el coeficient de correlació. 
# Informa’t-en sobre els seus usos i interpretació.

import numpy as np

print("EJERCICIO CORRELACIÓN")

def corr_coef(X, Y):
    r = (np.cov(X,Y)[0, 1])/(np.std(X,ddof=1)*np.std(Y,ddof=1))  #El elemento [0, 1] es el valor relevante para el cálculo 
    print("Coeficiente de Correlación: " + str(r))               #Es necesario usar ddof=1 en np.std porque retorna a estimativa imparcial
                                                                        #Con ddof= 0 (default) el resultado no es el mismo que en np.corrcoef 
    
X = np.random.randint(10, size=10)
Y = np.random.randint(10, size=10)

print("Array X: " + str(X))
print("Array Y: " + str(Y))
                             
corr_coef(X,Y)

print("Resultado de la funcion própria del Python: " + str(np.corrcoef(X,Y)[0, 1]))  # Cálculo realizado para confirmar el resultado de la funcion creada

# Resultado de la función es la medida de la correlación lineal entre dos conjuntos de datos
# Varia en el intervalo [-1, 1]. 
# r=1, correlación positiva perfecta / 0 < r < 1, correlación positiva/ r=0, no hay relación lineal
# -1 < r < 0, correlación negativa / r = -1, relación inversa
# Puede ser usada para verificar si hay relación entre dos variables observables y estimar la intensidad de su relación.


EJERCICIO CORRELACIÓN
Array X: [5 9 7 1 2 1 9 0 1 9]
Array Y: [0 2 5 0 4 1 4 9 0 8]
Coeficiente de Correlación: 0.21926957833558436
Resultado de la funcion própria del Python: 0.21926957833558436
